from typing import Any, Dict, Iterable, List, Mapping, Protocol

class Model(Protocol):
    def input_spec(self) -> Dict[str, Any]: ...
    def output_spec(self) -> Dict[str, Any]: ...
    def predict(
        self, _inputs: Iterable[Mapping[str, Any]], **kwargs: Any
    ) -> List[Mapping[str, Any]]: ...
